drop table if exists score cascade;
drop table if exists rubric_value cascade;
drop table if exists rubric cascade;
drop table if exists associate cascade;

create table associate (
	id serial primary key,
	first_name varchar(80),
	last_name varchar(80),
	secret_code varchar(6) unique not null
);
create table rubric (
	id serial primary key,
	theme varchar(80),
	description varchar(480)
);
create table rubric_value (
	id serial primary key,
	associate_id integer references associate,
	rubric_id integer references rubric,
	score integer check (score>-1 and score <6),
	description varchar(480)
);
create table score (
	id serial primary key,
	week integer,
	note varchar(480),
	rubric_id integer references rubric,
	associate_id integer references associate,
	score_value integer check(score_value>-1)
);

insert into rubric (id, theme, description) values 
(default, 'Product Marketing', 'incentivize back-end bandwidth'),
(default, 'DFD', 'orchestrate frictionless systems'),
(default, 'Navigation', 'repurpose customized communities'),
(default, 'Nielsen Data', 'maximize customized content'),
(default, 'Strategic HR', 'orchestrate plug-and-play supply-chains'),
(default, 'Theology', 'grow viral synergies');

insert into associate (id, first_name, last_name, secret_code) values 
(default, 'Patricia', 'Sketh', '403446'),
(default, 'Viki', 'Cooksley', '262217'),
(default, 'Celene', 'Slowley', '107631');

insert into rubric_value (id, associate_id, rubric_id, score, description) values 
 (default, 1, 1, 1, 'Aliquam quis turpis eget elit sodales scelerisque.'),
 (default, 1, 1, 2, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id defaulta ultrices aliquet.'),
 (default, 1, 1, 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.'),
 (default, 1, 1, 4, 'defaultam porttitor lacus at turpis.'),
 (default, 1, 1, 5, 'In hac habitasse platea dictumst.'),
 (default, 1, 2, 1, 'defaultam molestie nibh in lectus.'),
 (default, 1, 2, 2, 'Aenean lectus.'),
 (default, 1, 2, 3, 'Etiam faucibus cursus urna. Ut tellus.'),
 (default, 1, 2, 4, 'defaultam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.'),
 (default, 1, 2, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'),
 (default, 1, 3, 1, 'Donec dapibus.'),
 (default, 1, 3, 2, 'Donec dapibus. Duis at velit eu est congue elementum.'),
 (default, 1, 3, 3, 'Phasellus sit amet erat. defaulta tempus.'),
 (default, 1, 3, 4, 'Duis mattis egestas metus. Aenean fermentum.'),
 (default, 1, 3, 5, 'Integer ac leo. Pellentesque ultrices mattis odio.'),
 (default, 1, 4, 1, 'Sed sagittis.'),
 (default, 1, 4, 2, 'Etiam faucibus cursus urna. Ut tellus.'),
 (default, 1, 4, 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
 (default, 1, 4, 4, 'Aliquam quis turpis eget elit sodales scelerisque.'),
 (default, 1, 4, 5, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.'),
 (default, 1, 5, 1, 'Donec semper sapien a libero. Nam dui.'),
 (default, 1, 5, 2, 'Pellentesque eget nunc.'),
 (default, 1, 5, 3, 'Etiam justo.'),
 (default, 1, 5, 4, 'Aliquam non mauris.'),
 (default, 1, 5, 5, 'Suspendisse ornare consequat lectus.'),
 (default, 1, 6, 1, 'Duis consequat dui nec nisi volutpat eleifend.'),
 (default, 1, 6, 2, 'defaulta neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.'),
 (default, 1, 6, 3, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'),
 (default, 1, 6, 4, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.'),
 (default, 1, 6, 5, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.'),
 (default, 2, 1, 1, 'In eleifend quam a odio. In hac habitasse platea dictumst.'),
 (default, 2, 1, 2, 'Pellentesque at defaulta.'),
 (default, 2, 1, 3, 'Sed sagittis.'),
 (default, 2, 1, 4, 'Etiam vel augue.'),
 (default, 2, 1, 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.'),
 (default, 2, 2, 1, 'Nunc purus.'),
 (default, 2, 2, 2, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'),
 (default, 2, 2, 3, 'Aenean sit amet justo. Morbi ut odio.'),
 (default, 2, 2, 4, 'In sagittis dui vel nisl. Duis ac nibh.'),
 (default, 2, 2, 5, 'In sagittis dui vel nisl.'),
 (default, 2, 3, 1, 'Sed accumsan felis.'),
 (default, 2, 3, 2, 'defaulta mollis molestie lorem. Quisque ut erat.'),
 (default, 2, 3, 3, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.'),
 (default, 2, 3, 4, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.'),
 (default, 2, 3, 5, 'Etiam vel augue. Vestibulum rutrum rutrum neque.'),
 (default, 2, 4, 1, 'Sed sagittis.'),
 (default, 2, 4, 2, 'Mauris lacinia sapien quis libero. defaultam sit amet turpis elementum ligula vehicula consequat.'),
 (default, 2, 4, 3, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'),
 (default, 2, 4, 4, 'Suspendisse potenti.'),
 (default, 2, 4, 5, 'Curabitur at ipsum ac tellus semper interdum.'),
 (default, 2, 5, 1, 'Proin eu mi.'),
 (default, 2, 5, 2, 'Aliquam erat volutpat. In congue.'),
 (default, 2, 5, 3, 'Praesent id massa id nisl venenatis lacinia.'),
 (default, 2, 5, 4, 'Proin at turpis a pede posuere nonummy.'),
 (default, 2, 5, 5, 'In congue. Etiam justo.'),
 (default, 2, 6, 1, 'defaulta neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.'),
 (default, 2, 6, 2, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'),
 (default, 2, 6, 3, 'Suspendisse potenti. defaultam porttitor lacus at turpis.'),
 (default, 2, 6, 4, 'Curabitur gravida nisi at nibh.'),
 (default, 2, 6, 5, 'Quisque porta volutpat erat.'),
 (default, 3, 1, 1, 'Vestibulum rutrum rutrum neque.'),
 (default, 3, 1, 2, 'Donec ut dolor.'),
 (default, 3, 1, 3, 'Vivamus tortor.'),
 (default, 3, 1, 4, 'Morbi quis tortor id defaulta ultrices aliquet.'),
 (default, 3, 1, 5, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.'),
 (default, 3, 2, 1, 'Etiam faucibus cursus urna.'),
 (default, 3, 2, 2, 'Nam ultrices, libero non mattis pulvinar, defaulta pede ullamcorper augue, a suscipit defaulta elit ac defaulta.'),
 (default, 3, 2, 3, 'Vivamus vel defaulta eget eros elementum pellentesque. Quisque porta volutpat erat.'),
 (default, 3, 2, 4, 'Proin risus.'),
 (default, 3, 2, 5, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'),
 (default, 3, 3, 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'),
 (default, 3, 3, 2, 'Suspendisse accumsan tortor quis turpis.'),
 (default, 3, 3, 3, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.'),
 (default, 3, 3, 4, 'defaultam varius.'),
 (default, 3, 3, 5, 'defaulta facilisi. Cras non velit nec nisi vulputate nonummy.'),
 (default, 3, 4, 1, 'Donec vitae nisi.'),
 (default, 3, 4, 2, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
 (default, 3, 4, 3, 'Donec posuere metus vitae ipsum. Aliquam non mauris.'),
 (default, 3, 4, 4, 'Vivamus tortor.'),
 (default, 3, 4, 5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.'),
 (default, 3, 5, 1, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.'),
 (default, 3, 5, 2, 'Cras pellentesque volutpat dui.'),
 (default, 3, 5, 3, 'Praesent blandit.'),
 (default, 3, 5, 4, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.'),
 (default, 3, 5, 5, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'),
 (default, 3, 6, 1, 'Donec quis orci eget orci vehicula condimentum.'),
 (default, 3, 6, 2, 'defaulta suscipit ligula in lacus.'),
 (default, 3, 6, 3, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'),
 (default, 3, 6, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, defaulta. Sed accumsan felis.'),
 (default, 3, 6, 5, 'Pellentesque at defaulta.');
 
insert into score (id, week, note, rubric_id, associate_id, score_value) values 
(default, 2, 'Peruvian Dodder', 6, 3, 4),
(default, 3, 'Bog White Violet', 5, 2, 4),
(default, 2, 'New England Fontinalis Moss', 1, 2, 2),
(default, 7, 'Virginia Heartleaf', 2, 1, 2),
(default, 4, 'Mountain Misery', 6, 1, 2),
(default, 3, 'Fringed Lichen', 3, 1, 3),
(default, 5, 'West Indian Bristlegrass', 2, 1, 3),
(default, 9, 'Western Racomitrium Moss', 1, 3, 2),
(default, 8, 'Mediterranean Crownvetch', 6, 3, 2),
(default, 4, 'European Bur-reed', 3, 3, 2),
(default, 3, 'Dutchman''s Laudanum', 1, 1, 2),
(default, 2, 'Alaska Alkaligrass', 3, 2, 4),
(default, 7, 'Water Paspalum', 2, 3, 1),
(default, 9, 'Beautybush', 1, 1, 3),
(default, 8, 'Yellowspine Thistle', 5, 1, 3),
(default, 6, 'Cottonwood Springs Suncup', 1, 1, 2),
(default, 7, 'Creeping Willow', 2, 2, 1),
(default, 1, 'Pseudocrossidium Moss', 5, 1, 1),
(default, 9, 'Giant Milkvetch', 1, 1, 3),
(default, 3, 'Silver Cock''s Comb', 5, 2, 4),
(default, 8, 'Florida Reimar Grass', 4, 1, 4),
(default, 5, 'Trask''s Milkvetch', 6, 1, 2),
(default, 4, 'Big Island Ma''oloa', 1, 2, 1),
(default, 3, 'Threesection Buttercup', 5, 3, 4),
(default, 7, 'Tweedy''s Cat''s Ear', 1, 2, 4),
(default, 3, 'Laurel Sumac', 3, 2, 4),
(default, 1, 'Jesuit''s Bark', 4, 3, 4),
(default, 2, 'Showy Gentian', 3, 3, 1),
(default, 8, 'Simil Onion', 3, 1, 1),
(default, 9, 'Gennar''s Rinodina Lichen', 6, 2, 4);
 
 commit;